name: CI/CD for building, packaging and updating the DolphinOS repo

on: 
  workflow_dispatch:
  push:
    paths: 
      - ".github/workflows/update_repo.yaml"

permissions:
  contents: write
  packages: read
  pages: write

jobs:
  build_packages:
    name: Create and build Arch packages
    #runs-on: ["garunner", "self-hosted"]
    #runs-on: ubuntu-latest
    runs-on: self-hosted 

    container:
      image: ghcr.io/dolphinos-development/dolphinos-buildsystem-images/arch_repo__builder_image:latest
      options: --user 0:0

    steps:
    - name: Checkout repo (dolphinos-repo)
      uses: actions/checkout@v5
      with:
        path: repo

    - name: Checkout repo (DolphinOS-PKGBUILDs)
      uses: actions/checkout@v5
      with:
          repository: DolphinOS-Development/DolphinOS-PKGBUILDs
          path: pkgs

    - name: Fix workspace permissions
      working-directory: pkgs
      run: sudo chown -R builduser:builduser .

    - name: Clean repo directory
      working-directory: repo
      run: rm -rf x86_64/*.pkg.tar.zst

    - name: Build packages
      working-directory: pkgs
      run: |
        for pkg in */; do
          echo "==> Building $pkg"
          cd "$pkg"
          sudo -u builduser BUILDDIR=/build makepkg -sf --noconfirm
          mv ./*.pkg.tar.zst $GITHUB_WORKSPACE/repo/x86_64/
          rm -f /build/*.pkg.tar.zst
          cd -
        done

    - name: Update repo database
      working-directory: repo
      run: repo-add x86_64/dolphinos-repo.db.tar.gz x86_64/*.pkg.tar.zst
    
    - name: Commit changes and push packages to repo
      working-directory: repo
      run: |
        pwd
        ls
        sudo -u builduser git config user.name "github-actions[bot]"
        sudo -u builduser git config user.email "github-actions[bot]@users.noreply.github.com"
        sudo -u builduser git config http.postBuffer 3221225472
        sudo -u builduser git add x86_64/
        if sudo -u builduser git diff --cached --quiet; then
          echo "No changes to commit."
        else
          sudo -u builduser git commit -m "Update repo with latest package builds"
          sudo -u builduser git push
        fi
