name: CI/CD for building, packaging and updating the DolphinOS repo

on: 
  workflow_dispatch:
  push:
    paths: 
      - ".github/workflows/update_repo.yaml"

permissions:
  contents: write
  packages: read
  pages: write

jobs:
  build_packages:
    name: Create and build Arch packages
    runs-on: ["garunner", "self-hosted"] 

    container:
      image: ghcr.io/dolphinos-development/dolphinos-buildsystem-images/arch_repo__builder_image:latest
      options: --privileged

    steps:
    - name: Checkout repo (dolphinos-repo)
      uses: actions/checkout@v5
      with:
        path: repo

    - name: Checkout repo (DolphinOS-PKGBUILDs)
      uses: actions/checkout@v5
      with:
          repository: DolphinOS-Development/DolphinOS-PKGBUILDs
          path: pkgs

    - name: Build packages
      working-directory: pkgs
      run: |
        mkdir -p ../repo/x86_64
        for pkg in */; do
          echo "==> Building $pkg"
          cd "$pkg"
          makepkg -sf --noconfirm
          cp ./*.pkg.tar.zst ../../repo/x86_64/
          cd ..
        done

    - name: Update repo database
      working-directory: repo/x86_64
      run: |
        rm -f dolphinos.db* dolphinos.files*
        repo-add dolphinos.db.tar.gz *.pkg.tar.zst
    
    - name: Commit changes and push packages to repo
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config http.postBuffer 3221225472
        git add x86_64/
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update repo with latest package builds"
          git push
        fi
